default: &default
  adapter: postgresql
  username: fyber
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fyber_development

test:
  <<: *default
  database: fyber_test

production:
  <<: *default
  database: fyber_production
